FROM amazonlinux:2016.09

RUN yum update -y
RUN yum install -y \
    atlas-devel \
    atlas-sse3-devel \
    blas-devel \
    gcc \
    gcc-c++ \
    lapack-devel \
    findutils \
    zip

RUN yum -y install https://rhel6.iuscommunity.org/ius-release.rpm
RUN yum -y install \
    python36u \
    python36u-pip \
    python36u-devel \
    python36u-setuptools

ADD build3.6.sh /outputs/build.sh
ADD requirements.sh /outputs/requirements.sh

CMD /bin/bash /outputs/build.sh