FROM amazonlinux:2016.09

RUN yum update -y
RUN yum install -y \
    atlas-devel \
    atlas-sse3-devel \
    blas-devel \
    gcc \
    gcc-c++ \
    lapack-devel \
    python27-devel \
    python27-virtualenv \
    findutils \
    zip

ADD build.sh /outputs/build.sh
ADD requirements.sh /outputs/requirements.sh

CMD /bin/bash /outputs/build.sh
